### ISSUE TITLE
Error: unsupported Unicode escape sequence (SQLSTATE 22P05)" when querying Active directory

### ISSUE THREAD

**Issue by matteoredaelli** [turbot/steampipe-plugin-ldap#3] opened 2022-02-05 13:30 UTC
Hello I get the error: "Error: unsupported Unicode escape sequence (SQLSTATE 22P05)" when querying Active directory
How can I solve it?

```sql
select a.mail 
from ldap_user a 
where dn in (
  select 
    jsonb_array_elements_text(attributes -> 'manager')
  from adgroup.ldap_user where sam_account_name='matteo');
```

The single queries work fine

```sql
select  jsonb_array_elements_text(attributes -> 'manager')
from
  adgroup.ldap_user where sam_account_name='matteo';
```

```text
+------------------------------------------------------------------------------------------------------------------+
| jsonb_array_elements_text                                                                                        |
+------------------------------------------------------------------------------------------------------------------+
| CN=Pippo,DC=redaelli,DC=com |
+------------------------------------------------------------------------------------------------------------------+
```

```sql
 select a.mail 
from ldap_user a where dn  in ('CN=..');
```

```text
+---------------------------+
| mail                      |
+---------------------------+
| pippo@example.com |
+---------------------------+
```

**Comment by matteoredaelli** [comment] 2022-02-08 14:55
See also the thread on  slack   https://steampipe.slack.com/archives/C01UECB59A7/p1644008073746389

**Comment by matteoredaelli** [comment] 2022-03-30 17:47
Hello I get the same error with

```
matteo@debian:~$ steampipe query
Welcome to Steampipe v0.13.3
For more information, type .help
> select sam_account_name
from
  ldap_group
where sam_account_name like 'Qliksense_%';
Error: unsupported Unicode escape sequence (SQLSTATE 22P05)
```


With sqlline & postgres jdbc driver I get

```
0: jdbc:postgresql://localhost:9193/steampipe> select sam_account_name
. . . . . . . . . . . . . . . . . . semicolon> from
. . . . . . . . . . . . . . . . . . semicolon>   ldap_group
. . . . . . . . . . . . . . . . . . semicolon> where sam_account_name like 'Qliksense_%'
. . . . . . . . . . . . . . . . . . semicolon> ;
Error: ERROR: unsupported Unicode escape sequence
  Detail: \u0000 cannot be converted to text.
  Where: JSON data, line 1: ...om"],"objectClass":["top","group"],"objectGUID":[... (state=22P05,code=0)
```


My database*.log is

```
******************************************************

		steampipe postgres fdw init

******************************************************
2022/03/30 19:40:56 [INFO] Log level WARN
2022-03-30 17:41:09.945 UTC [93175] ERROR:  unsupported Unicode escape sequence
2022-03-30 17:41:09.945 UTC [93175] DETAIL:  \u0000 cannot be converted to text.
2022-03-30 17:41:09.945 UTC [93175] CONTEXT:  JSON data, line 1: ...om"],"objectClass":["top","group"],"objectGUID":[...
2022-03-30 17:41:09.945 UTC [93175] STATEMENT:  select sam_account_name
	from
	  ldap_group
	where sam_account_name like 'Qliksense_%';
2022-03-30 17:44:07.691 UTC [93175] ERROR:  unsupported Unicode escape sequence
2022-03-30 17:44:07.691 UTC [93175] DETAIL:  \u0000 cannot be converted to text.
2022-03-30 17:44:07.691 UTC [93175] CONTEXT:  JSON data, line 1: ...om"],"objectClass":["top","group"],"objectGUID":[...
2022-03-30 17:44:07.691 UTC [93175] STATEMENT:  select sam_account_name
	from
	  ldap_group
	where sam_account_name like 'Qliksense_%';
2022-03-30 17:44:35.695 UTC [93175] LOG:  disconnection: session time: 0:04:03.204 user=steampipe database=steampipe host=127.0.0.1 port=47746

```

**Comment by cbruno10** [comment] 2022-03-30 18:00
@matteoredaelli Sorry for the long silence on this one. I'm not sure if a fix is required in this plugin and/or our Postgres FDW, but we do currently have a bug open in our [FDW repo](https://github.com/turbot/steampipe-postgres-fdw/issues/118) that may resolve this issue. I've commented in that issue and will follow-up further to see where the fix(es) are required. I'll echo any updates in that issue back in this one as well for tracking purposes.

**Comment by cbruno10** [comment] 2022-05-10 12:54
@matteoredaelli We released Steampipe v0.14.0 yesterday, which fixed some unicode escape sequence errors like the one you were seeing above. When you get a chance, can you please download the latest version of Steampipe and run the same queries? If you're still getting an error, feel free to re-open this issue and we'll have another look, thanks!

**Comment by christianherweg0807** [comment] 2022-06-21 14:27
I think the Problem is still there :
```
$ steampipe -v
steampipe version 0.14.6
```
Here an example with latest ldap plugin running against an Microsoft AD LDAP:
```
> select mail from ldap_user where department like 'MY-DE-PA-RT-MENT';
**Error: unsupported Unicode escape sequence (SQLSTATE 22P05)**
> select mail from ldap_user where department = 'MY-DE-PA-RT-MENT';
+-----------------------------+
| mail                        |
+-----------------------------+
| someone.somewhere@mail.de    |
```

**Comment by cbruno10** [comment] 2022-06-21 17:18
@christianherweg0807 Thanks for reporting there's still an issue, and sorry that it's still there! I'll re-open https://github.com/turbot/steampipe-postgres-fdw/issues/118 and add your comment in there, can you please follow-up in that issue with anymore information/questions, as that's the proper repo to fix it in I believe. Thanks!

**Comment by cbruno10** [comment] 2022-06-21 17:21
Accidentally re-opened and assigned the wrong person here, re-closing so we can continue discussion in https://github.com/turbot/steampipe-postgres-fdw/issues/118.

**Closed as completed by cbruno10** 2022-06-21 17:21 UTC
Labels: bug
